# Generated by Django 5.0.6 on 2024-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="no",
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name="系统订单号"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="out_no",
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name="商户订单号"),
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="proj",
        ),
    ]
