# Generated by Django 5.0.6 on 2024-06-25 15:12

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(help_text="例如：USDT、UNI", max_length=8, unique=True, verbose_name="代号")),
                ("decimals", models.PositiveSmallIntegerField(default=18, verbose_name="精度")),
                (
                    "price_in_usdt",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=32, null=True, verbose_name="价格（USD）"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Base", "主币"), ("ERC20", "ERC20")], default="ERC20", editable=False, max_length=8
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="是否启用本代币（仅对主币生效）", verbose_name="启用")),
            ],
            options={
                "verbose_name": "代币",
                "verbose_name_plural": "代币",
            },
        ),
        migrations.CreateModel(
            name="TokenAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", common.fields.ChecksumAddressField(db_index=True, max_length=42, verbose_name="代币地址")),
                ("active", models.BooleanField(default=True, help_text="是否启用本代币（仅对ERC20生效）", verbose_name="启用")),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chains.network", verbose_name="所在的网络"
                    ),
                ),
                ("token", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tokens.token")),
            ],
            options={
                "verbose_name": "代币地址",
                "verbose_name_plural": "代币地址",
                "unique_together": {("token", "network")},
            },
        ),
        migrations.AddField(
            model_name="token",
            name="networks",
            field=models.ManyToManyField(related_name="tokens", through="tokens.TokenAddress", to="chains.network"),
        ),
        migrations.CreateModel(
            name="TokenTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_address",
                    common.fields.ChecksumAddressField(db_index=True, max_length=42, verbose_name="From"),
                ),
                ("to_address", common.fields.ChecksumAddressField(db_index=True, max_length=42, verbose_name="To")),
                ("value", models.DecimalField(decimal_places=0, default=0, max_digits=36)),
                ("token", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tokens.token")),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_transfer",
                        to="chains.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "转移",
                "verbose_name_plural": "转移",
            },
        ),
        migrations.CreateModel(
            name="AccountTokenBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=0, default=0, max_digits=36)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="chains.account")),
                ("network", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="chains.network")),
                ("token", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tokens.token")),
            ],
            options={
                "verbose_name": "余额",
                "verbose_name_plural": "余额",
                "unique_together": {("account", "network", "token")},
            },
        ),
    ]
