# Generated by Django 5.0.6 on 2024-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.CharField(
                choices=[("Base", "主币"), ("ERC20", "ERC20")],
                default="ERC20",
                editable=False,
                max_length=8,
                verbose_name="类型",
            ),
        ),
    ]
