# Generated by Django 5.0.6 on 2024-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0003_alter_chain_active"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="chains",
            field=models.ManyToManyField(
                help_text="记录代币在每个公链上的地址，原生代币地址默认为0x0地址",
                related_name="tokens",
                through="tokens.TokenAddress",
                to="chains.chain",
            ),
        ),
        migrations.AlterField(
            model_name="tokenaddress",
            name="active",
            field=models.BooleanField(default=True, help_text="关闭将会停止此链上与本代币相关接口的调用", verbose_name="启用"),
        ),
    ]
