# Generated by Django 5.0.1 on 2024-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="symbol",
            field=models.CharField(help_text="例如：USDT、UNI", max_length=32, unique=True, verbose_name="代号"),
        ),
    ]
