# Generated by Django 5.0.6 on 2024-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_alter_token_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="price_in_usdt",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name="价格（USD）"),
        ),
    ]
