# Generated by Django 5.0.6 on 2024-06-21 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_alter_token_price_in_usdt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttokenbalance",
            options={"verbose_name": "余额", "verbose_name_plural": "余额"},
        ),
        migrations.AlterModelOptions(
            name="tokentransfer",
            options={"verbose_name": "转移", "verbose_name_plural": "转移"},
        ),
    ]
