# Generated by Django 5.0.1 on 2024-02-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="related_proj",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="globals.project"
            ),
        ),
        migrations.AddField(
            model_name="platformtransaction",
            name="transaction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_tx",
                to="chains.transaction",
                verbose_name="交易",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("network", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="platformtransaction",
            unique_together={("account", "network", "nonce")},
        ),
    ]
