# Generated by Django 5.0.6 on 2024-06-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="currency",
            field=models.OneToOneField(
                blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to="tokens.token"
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="network",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="chains.network"),
        ),
        migrations.AddField(
            model_name="platformtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chains.account", verbose_name="账户"
            ),
        ),
        migrations.AddField(
            model_name="platformtransaction",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chains.network", verbose_name="网络"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="chains.block"
            ),
        ),
        migrations.AddField(
            model_name="platformtransaction",
            name="transaction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_tx",
                to="chains.transaction",
                verbose_name="交易",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("network", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="platformtransaction",
            unique_together={("account", "network", "nonce")},
        ),
    ]
