# Generated by Django 5.0.6 on 2024-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="active",
            field=models.BooleanField(default=True, help_text="关闭将会停止接受此链出块信息，且停止与其相关的接口调用", verbose_name="启用"),
        ),
    ]
