# Generated by Django 5.0.6 on 2024-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paying", "支付账单"),
                    ("depositing", "玩家充币"),
                    ("withdrawal", "玩家提币"),
                    ("funding", "注入资金"),
                    ("gas_recharging", "Gas分发"),
                    ("d_gathering", "充币归集"),
                    ("i_gathering", "账单归集"),
                ],
                max_length=16,
                null=True,
                verbose_name="类型",
            ),
        ),
    ]
