# Generated by Django 5.0.6 on 2024-06-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_alter_chain_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformtransaction",
            name="hash",
        ),
    ]
