# Generated by Django 5.0.6 on 2024-06-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0003_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionqueue",
            options={"ordering": ("created_at",), "verbose_name": "执行队列", "verbose_name_plural": "执行队列"},
        ),
        migrations.AlterField(
            model_name="block",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chains.chain", verbose_name="公链"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="已确认"),
        ),
        migrations.AlterField(
            model_name="block",
            name="number",
            field=models.PositiveIntegerField(db_index=True, verbose_name="区块号"),
        ),
        migrations.AlterField(
            model_name="block",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.block",
                verbose_name="父区块",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="timestamp",
            field=models.PositiveIntegerField(verbose_name="时间戳"),
        ),
    ]
