# Generated by Django 5.0.6 on 2024-06-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0004_remove_platformtransaction_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformtransaction",
            name="gas",
        ),
    ]
