# Generated by Django 5.0.6 on 2024-06-21 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0003_alter_network_options_and_more"),
        ("deposits", "0003_rename_user_deposit_player"),
        ("globals", "0002_alter_project_notification_failed_times"),
        ("users", "0001_initial"),
        ("withdrawals", "0002_rename_user_withdrawal_player"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Player",
        ),
    ]
