# Generated by Django 5.0.6 on 2024-06-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0004_remove_platformtransaction_hash"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="deposit_account",
            field=models.OneToOneField(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="chains.account", verbose_name="充币地址"
            ),
        ),
    ]
