# Generated by Django 5.0.6 on 2024-06-21 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0002_alter_project_notification_failed_times"),
        ("users", "0002_rename_user_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="username",
            new_name="uid",
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("uid", "proj")},
        ),
    ]
