# Generated by Django 5.0.6 on 2024-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_username_player_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="uid",
            field=models.CharField(db_index=True, max_length=42, verbose_name="用户UID"),
        ),
    ]
