# Generated by Django 5.0.6 on 2024-06-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_player_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="uid",
            field=models.CharField(db_index=True, max_length=64, verbose_name="玩家UID"),
        ),
    ]
