# Generated by Django 5.0.6 on 2024-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_player_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="player",
            name="uid",
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name="玩家UID"),
        ),
        migrations.RemoveField(
            model_name="player",
            name="proj",
        ),
    ]
