# Generated by Django 5.0.6 on 2024-06-25 15:12

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0002_initial"),
        ("tokens", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=8, max_digits=32, verbose_name="数量")),
                ("no", models.CharField(max_length=64, unique=True, verbose_name="编号")),
                ("to", common.fields.ChecksumAddressField(db_index=True, max_length=42, verbose_name="收币地址")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "platform_tx",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="chains.platformtransaction", verbose_name="交易"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.player", verbose_name="用户"
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tokens.token", verbose_name="代币"
                    ),
                ),
            ],
            options={
                "verbose_name": "提币",
                "verbose_name_plural": "提币",
            },
        ),
    ]
