# Generated by Django 5.0.1 on 2024-02-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("tokens", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=8, max_digits=32, verbose_name="数量")),
                ("no", models.CharField(max_length=64, unique=True, verbose_name="账单号")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "platform_tx",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.platformtransaction",
                        verbose_name="交易队列",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tokens.token", verbose_name="代币"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user", verbose_name="用户"),
                ),
            ],
            options={
                "verbose_name": "提币",
                "verbose_name_plural": "提币",
            },
        ),
    ]
