# Generated by Django 5.0.6 on 2024-06-21 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="withdrawal",
            old_name="user",
            new_name="player",
        ),
    ]
