# Generated by Django 5.0.6 on 2024-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="status",
            field=models.CharField(
                choices=[("Waiting", "待执行"), ("Success", "成功")], default="Waiting", max_length=16, verbose_name="状态"
            ),
        ),
    ]
