# Generated by Django 5.0.6 on 2024-06-27 10:34

from django.db import migrations


def fill_status(apps, schema_editor):
    Withdrawal = apps.get_model("withdrawals", "Withdrawal")
    for withdrawal in Withdrawal.objects.all():
        withdrawal.status = "Success"
        withdrawal.save()


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0002_withdrawal_status"),
    ]

    operations = [migrations.RunPython(fill_status)]
