# Generated by Django 5.0.6 on 2024-06-27 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("withdrawals", "0003_auto_20240627_1034"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawal",
            name="status",
        ),
    ]
