# Generated by Django 5.0.1 on 2024-02-26 11:06

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appid", models.CharField(max_length=32, unique=True, verbose_name="appid")),
                (
                    "ip_white_list",
                    models.TextField(
                        help_text="只有符合白名单的 IP 才可以与本网关交互；<br/>支持 IP 地址或 IP 网段；<br/>可同时设置多个，中间用英文逗号','分割；<br/>",
                        null=True,
                        verbose_name="IP白名单",
                    ),
                ),
                (
                    "webhook",
                    models.CharField(
                        help_text="用于本网关发送通知到项目后端；", max_length=256, null=True, verbose_name="Webhook回调地址"
                    ),
                ),
                (
                    "notification_failed_times",
                    models.PositiveIntegerField(default=0, verbose_name="连续通知失败的次数，超过32次则不再发送通知，直到手动置为零；"),
                ),
                ("pre_notify", models.BooleanField(default=False, verbose_name="开启预通知")),
                ("hmac_key", models.CharField(help_text="用于本网关与项目后端的交互签名；", max_length=256, verbose_name="HMAC密钥")),
                (
                    "collection_address",
                    common.fields.ChecksumAddressField(
                        db_index=True, help_text="用户支付的代币，将归集到此地址；", max_length=42, null=True, verbose_name="代币归集地址"
                    ),
                ),
                (
                    "distribution_account",
                    models.OneToOneField(
                        help_text="提币时，系统通过此账户发送代币到用户地址；<br/>要保证此地址的 Gas 和各代币充盈，否则提币无法成功；",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proj",
                        to="chains.account",
                        verbose_name="金库账户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目配置",
                "verbose_name_plural": "项目配置",
            },
        ),
    ]
