# Generated by Django 5.0.6 on 2024-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="notification_failed_times",
            field=models.PositiveIntegerField(default=0, help_text="超过32次则不再发送通知，直到手动置为零；", verbose_name="连续通知失败的次数"),
        ),
    ]
