# Generated by Django 5.0.6 on 2024-06-21 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0002_alter_project_notification_failed_times"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="appid",
        ),
    ]
