# Generated by Django 5.0.6 on 2024-06-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0004_remove_transaction_related_proj_and_more"),
        ("globals", "0004_alter_project_distribution_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="distribution_account",
            field=models.OneToOneField(
                help_text="提币时，系统通过此账户发送代币到用户地址；<br/>要保证此地址的 Gas 和各代币充盈，否则提币无法成功；",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project",
                to="chains.account",
                verbose_name="分发账户",
            ),
        ),
    ]
