# Generated by Django 5.0.6 on 2024-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0005_alter_project_distribution_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="webhook",
            field=models.URLField(help_text="用于本网关发送通知到项目后端；", max_length=256, null=True, verbose_name="Webhook回调地址"),
        ),
    ]
