# Generated by Django 5.0.1 on 2024-02-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.JSONField()),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="chains.transaction"),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
