# Generated by Django 5.0.6 on 2024-06-19 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("created_at",), "verbose_name": "回调通知", "verbose_name_plural": "回调通知"},
        ),
    ]
